### ISSUE TITLE
Static ctor in MyWebApi renders library unusable when used with custom route constraints

### ISSUE THREAD

**Issue by paulsuart** [ivaylokenov/MyTested.WebApi#270] opened 2017-03-08 08:47 UTC
I am attempting to use MyTested.WebApi to test routing in my Web API project, which contains custom route constraints on attribute-based routes, e.g.:

`[Route("{templateId:int}/{reportId:keyint}")]` where `keyint` is a custom constraint registered as follows:

```
var constraintResolver = new DefaultInlineConstraintResolver();
// KeyWebApiInt32Constraint is my custom constraint type.
constraintResolver.ConstraintMap.Add("keyint", typeof(KeyWebApiInt32Constraint));
config.MapHttpAttributeRoutes(constraintResolver);
```

As soon as any type in the `MyTested.WebApi` assembly is loaded, this static ctor runs:

```
static MyWebApi()
{
    IsUsingDefaultHttpConfiguration();
}
```

This in turn calls `config.MapHttpAttributeRoutes();` which uses a default instance of `DefaultInlineConstraintResolver` internally.  This constraint resolver is unable to resolve my constraint, which causes an exception to be thrown.  This exception causes the static constructor to fail, which causes a `TypeInitializationException` and the library is unusable.

It would be good if the static constructor could be eliminated.  I'm struggling to see the value it's adding.

**Comment by ivaylokenov** [comment] 2017-04-12 08:19
@paulsuart Thank you for your feedback. Sorry for the late reply. Do you have any suggestions for any improvements? In my other library, there are other options to initialize a test, for example `new MyController<TController>()`. I will take a look to see what I can improve.

**Comment by spasm** [comment] 2017-06-27 00:04
Anyone have a work around for this yet?  I ran into this today trying to use the Microsoft WebAPI Versioning package .. the apiVersion route constraint will cause this issue to be hit.  I see @paulsuart has submitted a PR however it hasn't been merged yet.  Any ETA?  This is a fantastic testing library however I had resort to not using it due to this behavior.

**Comment by paulsuart** [comment] 2017-06-27 07:53
@spasm - yep I have a workaround 😄 

No idea when, or even if, my PR is going to be looked at.

**Comment by keyau** [comment] 2017-07-12 21:11
@ivaylokenov I have the same error with apiVersion route constraint and I am also interested in PR from @paulsuart.

**Comment by vip32** [comment] 2018-03-23 17:03
almost a year later i was also hit by this problem (due to adding apiversioning). @ivaylokenov, what are the plans for the PR? this really is a lovely tool to make api testing nicer and less verbose, pitty that it seems dead in the water :(

**Comment by paulsuart** [comment] 2018-03-24 19:46
@vip32 it must be in my fork as that's the source of the PR. No nuget package unfortunately.

**Comment by vip32** [comment] 2018-03-26 19:56
Thx, found it already

**Comment by ivaylokenov** [comment] 2019-07-09 16:24
@vip32 @paulsuart @spasm @keyau 

Hi guys,

I will get into all issues in the library in the next few weeks and try to publish a new package. 

I noticed @vip32 has another version published with a fix, which is very nice! Is there anything else added to that package which is missing here too? So that I can add it here as well?

I will try to explain why the code was delayed by so much time.

Back in March 2017 when .NET Core migrated to the new (old) .csproj file format, I was having difficulties with the other project.

Visual Studio was continually crashing, tests did not run correctly, and the overall developing experience was terrible. I tried for 2-3 months to port the library but could not succeed.

During that time, I started developing severe health issues from staying in front of my computer too much. I was working 12 to 16 hours from Monday to Sunday with not many breaks for 2-3 years straight. I had to stop doing it for an indefinite time. My GitHub activity shows this pretty clearly: https://github.com/ivaylokenov

The truth is - I like my testing libraries and have much fun developing them, so I was confused and did not know what to tell people about their future maintenance. I did not want to abandon them forever but did not know when I would be able to work actively again on it. I now realize that it was a mistake to be silent all this time and should have put an explanation earlier. The fact that my personal life was very stressful for the last two years is not an excuse.

Back in October 2018, I opened the code and started working actively on bringing back the libraries to life. It took me 6 months because I added lots of new features like third-party DI support, all possible action results, every single action filter, lots of helper methods for easier testing, more straightforward configuration, performance fixes and more. Version 2.2 of the .NET Core testing library is available on NuGet already, and version 2.1 will be published in the next few days. I will then update the tutorial, documentation, the web site, and will start working on .NET Core 3. The WebApi library will be revisited too with all the issues that were logged here by its users.

I am sorry for the inconvenience caused by this library and me. I truly am.

The good news is that I found a small private investor who is sponsoring the projects. I can actively put 20 to 30 hours per week in the development of the libraries. If I manage to increase the usage and find clients, the investor will increase the budget and I will be able to hire another developer to help me. Additionally, I will put a sponsorship program with logos, and hopefully, I will be able to maintain the project steadily in the years to come.

Thank you for reading and understanding.

Ivaylo

**Comment by paulsuart** [comment] 2019-07-10 08:59
Hi @ivaylokenov.  Thanks for your detailed and honest comment.  In summary: you absolutely did the right thing and took time out to look after yourself (and I wholeheartedly agree that the switch to .NET Core in early 2017 was an absolute nightmare!).

All the best!

**Comment by vip32** [comment] 2019-07-10 09:41
Hi @ivaylokenov  good to see you are back on track :) now take it easy and very important :> take breaks! good solutions always come when there is some room for it.

will soon try the your new netcore stuff, for now i am stuck with net47. unfortunately i had to fork /publish ([nuget](https://www.nuget.org/packages/MyTested.WebApi2/)) your work due to issues.  its been a while but i think it was due to our net45 > net47 migration.

**Comment by ivaylokenov** [comment] 2019-07-11 16:12
@paulsuart @vip32 Thank you very much for the nice words! :)

Ok, @vip32 - I will take a look at your commits and will add everything you did to this repo too. Will see all other issues. 

Thank you again!

**Closed** 2019-09-02 11:36 UTC
Labels: bug
